### ISSUE TITLE
[FEATURE]: 地震台播报

### ISSUE THREAD

**Issue by z0z0r4** [Teahouse-Studios/akari-bot#1006]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

https://www.ceic.ac.cn/speedsearch

地震台播报，轮询接口，查询是否有新的地震

### 实现方法

https://www.ceic.ac.cn/daochu/id:0 全站数据在此

具体的每天等具体数据直接抓就行

### 接口

https://www.ceic.ac.cn/speedsearch

### 备注

寒假计划做，挖个坑

**Comment by DoroWolf** [comment]
倾向否决：地域局限性较强

**Comment by z0z0r4** [comment]
> 倾向否决：地域局限性较强

你指的是仅限国内？可以接入多个的吧？
