### ISSUE TITLE
[REQUEST]: Wiki链接白名单申请

### ISSUE THREAD

**Issue by JesKi13567** [Teahouse-Studios/akari-bot#1013]
### 开始之前……

- [X] 我已确定此 Wiki 中的内容没有任何涉嫌政治、色情、谩骂、暴力等不良内容。

### Wiki 链接

https://zh.minecraft.wiki/

### 备注

本地址已将fandom上的内容全部搬运了，且更快。

**Comment by Dianliang233** [comment]
请问你是从哪听说的这个？

**Comment by JesKi13567** [comment]
> 请问你是从哪听说的这个？

  mcbbs之前不是说wiki搬运，到minecraft.wiki出现，再到我隔段时间在minecraft.wiki上查看语言，今天发现有了

**Comment by Dianliang233** [comment]
done
