### ISSUE TITLE
[FEATURE]: 更改 `Image` 消息类型在 QQ 的传输的方式

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#1059]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

目前 QQ 的 `Image` 类型是使用路径来传输的。

但是有些时候（使用 OpenShamrock（类似于 go-cqhttp 且能支持部分 go-cqhttp 的消息类型的一个 QQ 机器人框架） 时，由于 Python 依赖的原因，小可和 OpenShamerock 不在同一设备上）难以使用路径的方式来传输图片。

需要一种新的图片传输方式来解决问题。

### 实现方法

根据 go-cqhttp 的消息类型文档：

https://docs.go-cqhttp.org/cqcode/#%E5%9B%BE%E7%89%87

![image](https://github.com/Teahouse-Studios/akari-bot/assets/113701655/f62c6b97-0c60-471f-83d9-581f750d211d)

是否可以使用 Base64 编码来进行图片传输？

**Comment by OasisAkari** [comment]
https://github.com/Teahouse-Studios/akari-bot/blob/master/bots/lagrange/message.py#L114

其实对接到lagrange的代码有用到base64传输，只不过对接gocq那一侧的没有

**Comment by SilianZ** [comment]
> https://github.com/Teahouse-Studios/akari-bot/blob/master/bots/lagrange/message.py#L114
> 
> 其实对接到lagrange的代码有用到base64传输，只不过对接gocq那一侧的没有

那么该如何解决？

**Comment by OasisAkari** [comment]
改成用base64传输了，你可以看看问题有没有解决

**Comment by OasisAkari** [comment]
> https://github.com/Teahouse-Studios/akari-bot/blob/master/bots/lagrange/message.py#L114
> 
> 其实对接到lagrange的代码有用到base64传输，只不过对接gocq那一侧的没有

言外之意是我没有改的原因是因为它在我这边工作良好所以我懒得改（。）

**Comment by OasisAkari** [comment]
我觉得应该是没有问题了所以我close了
