### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by OasisAkari** [Teahouse-Studios/akari-bot#1100]
![8c428fec6f982ad90356805d19faf698](https://github.com/Teahouse-Studios/akari-bot/assets/31803608/650749a6-e61b-43d6-8aee-ecedbbe5fef8)

todo

链接实际指向minecraft wiki而非Wikipedia

**Comment by DoroWolf** [comment]
此iw不在自定义iw列表中，推测为默认API自带iw重定向导致
