### ISSUE TITLE
[BUG]: weekly_rss问题

### ISSUE THREAD

**Issue by DoroWolf** [Teahouse-Studios/akari-bot#1105]
如图，部分信息已脱敏处理
![IMG_20240212_100727](https://github.com/Teahouse-Studios/akari-bot/assets/61273857/83b24ff5-2b14-4986-9db5-875322cbc974)

**Comment by OasisAkari** [comment]
db44565c36ddf95f9e387cf940396a0f3ebd8e7c

目前JobQueue无法自动识别参数中的MessageChain，暂时需要手动转换为dict再进行发送
