### ISSUE TITLE
将secret模块改为wiki_rss

### ISSUE THREAD

**Issue by DoroWolf** [Teahouse-Studios/akari-bot#1113]
由于mcw对滥用日志采用保护，原先的secret模块就失去其该有的用途。
但是删除掉又觉得可惜，考虑改为wiki_rss，并查询对话已绑定的Wiki，向QQ以外的平台对外开放，QQ平台由于风控问题仍然保持仅超级用户权限。

**Comment by OasisAkari** [comment]
e那啥...模块其实还是在用的但是不是在那个群用了

**Comment by DoroWolf** [comment]
重定向issue#960
