### ISSUE TITLE
webhook支持

### ISSUE THREAD

**Issue by OasisAkari** [Teahouse-Studios/akari-bot#114]

**Comment by HornCopper** [comment]
请问是JSON还是另外那个（名字又臭又长的那个）

**Comment by OasisAkari** [comment]
得先引入一个web框架（...）

然后似乎只有flask和quart可以选（......）

flask对async的支持不如quart，所以似乎就只有一种选择了（.........）

quart又莫名其妙不兼容docopt（？）（............）

似乎这个得把命令解析解决了才能做了（.......................................）

**Comment by Dianliang233** [comment]
我不觉得使用 webhook 比较合适吧...

主要 webhook 是单向通信

**Comment by HornCopper** [comment]
> 得先引入一个web框架（...）
> 
> 然后似乎只有flask和quart可以选（......）
> 
> flask对async的支持不如quart，所以似乎就只有一种选择了（.........）
> 
> quart又莫名其妙不兼容docopt（？）（............）
> 
> 似乎这个得把命令解析解决了才能做了（.......................................）

用FastAPI可以吗（小声）

**Comment by Dianliang233** [comment]
建议改用 WebSocket

**Comment by OasisAkari** [comment]
近期想个办法支持一下，看到了crowdin的webhook api，感觉可以拿来用用

**Comment by OasisAkari** [comment]
crowdin的webhook要owner才能配置，溜了溜了）

**Comment by OasisAkari** [comment]
现在利用jobqueue完全可以简单实现webhook机制 但是目前貌似并没有实际场景需要
还是关掉这个issue好了）
