### ISSUE TITLE
[FEATURE]: 警告用户时附上服务条款链接

### ISSUE THREAD

**Issue by MC-luoluo** [Teahouse-Studios/akari-bot#1176]
### 开始之前……

- [X] 我已在 [Issue](https://github.com/Teahouse-Studios/bot/issues) 中搜索过我的建议，确定没有人提出过此建议。

### 建议描述

建议在警告用户时附上服务条款的链接，引导用户查看并遵守服务条款

目前样式：
![图片](https://github.com/Teahouse-Studios/akari-bot/assets/113677351/c4b2a58f-9b34-494d-a3f0-9ed0e11bfdec)

**Comment by DoroWolf** [comment]
没什么打算，而且不想在多语言和配置文件多一个重要性不太强的项目了。
而且不刷屏、不踢群和禁言应该算是引入qq机器人的共识
