### ISSUE TITLE
[BUG]: weekly无法正常工作

### ISSUE THREAD

**Issue by DoroWolf** [Teahouse-Studios/akari-bot#1189]
不知道是格式改动还是什么原因，现在weekly没法正常工作，而且也没法正常获取图片。

**Comment by OasisAkari** [comment]
1. weelky获取页面链接的逻辑是截取文本内第一个加粗文本的链接，但这周的文本并没有加粗
2. 图片格式似乎存在某种改动

**Comment by AlPha5130** [comment]
你需要了解下wmf搞出来的媒体结构-_-

**Comment by AlPha5130** [comment]
https://www.mediawiki.org/wiki/Parsoid/Parser_Unification/Media_structure/FAQ

**Comment by Leo-768** [comment]
https://github.com/Teahouse-Studios/akari-bot/commit/161d3b7fe4c119d924775cecc810ededec6c1294 後，weekly會無視加粗連結，無法正確取得每週頁面連結。

取消原本加粗偵測並不必要，因為前天沒有加粗的原因就是因為沒有每週頁面，取得不到每週頁面才該是正常行為。
