### ISSUE TITLE
[BUG]: 机器人报错

### ISSUE THREAD

**Issue by caoTbenren0** [Teahouse-Studios/akari-bot#1209]
### 开始之前……

- [X] 我已在 [Issue](https://github.com/Teahouse-Studios/bot/issues) 中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法。

### 聊天平台

QQ 群

### 用户 ID

QQ|1479446126

### 对话 ID

QQ|Group|961399507

### 错误信息

执行命令时发生错误：
Session must be Bot.MessageSession or QueryInfo.
请将此信息报告给机器人开发者。
错误汇报地址：https://s.wd-ljt.com/botreportbug

### 错误描述

我正在使用小可执行搜索指令"~wiki search <minecraft>"时正常返回了"搜索结果：
1. Mojang Studios
2. Java版
3. Minecraft
4. 基岩版
5. 演示模式
6. Minecraft Dungeons
7. PC Gamer演示版
8. Java版Beta
9. Java版pre-Classic
10. Minecraft Infdev
回复编号以查询对应的页面。
（请使用指定的词语回复本条消息）"
随后回复1便报错了

### 复现方法

1.执行~wiki search <任意关键词>
2.回复任意搜索结果的序号
3.报错

### 本应发生的结果

返回wiki上关于mojang工作室的信息

### 备注

![Uploading Image_1720254810767.png…]()

**Comment by DoroWolf** [comment]
修改数组越界问题时改错了，已修复
