### ISSUE TITLE
加群申请

### ISSUE THREAD

**Issue by 2333inksans** [Teahouse-Studios/akari-bot#1220]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [X] 我是群聊的管理员，或群主或管理员允许机器人入群

### QQ号

3837705087

### QQ群

695173970

### 入群方式

没有，加入后需要管理员或群主同意

### 群主或管理员同意

我是本群的管理员

### 备注

没了

**Comment by DoroWolf** [comment]
已发送请求，请检查是否收到

**Comment by 2333inksans** [comment]
收到

**Comment by 2333inksans** [comment]
没事了我没看到通知....
