### ISSUE TITLE
[NEW]: 加入新群

### ISSUE THREAD

**Issue by M397749490** [Teahouse-Studios/akari-bot#1234]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [X] 我是群聊的管理员，或群主或管理员允许机器人入群

### QQ号

397749490

### QQ群

512921054

### 入群方式

有特殊答案，答案为 小可

### 群主或管理员同意

我是本群的管理员

**Comment by DoroWolf** [comment]
已发送申请，请检查是否收到

**Comment by DoroWolf** [comment]
已发送申请，请检查是否收到
