### ISSUE TITLE
[BUG]: 添加wiki页面时出现问题

### ISSUE THREAD

**Issue by zwz211123** [Teahouse-Studios/akari-bot#1235]
### 开始之前……

- [X] 我已在 [Issue](https://github.com/Teahouse-Studios/bot/issues) 中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法。

### 聊天平台

Discord

### 用户 ID

Discord|Client|1188426494578528307

### 对话 ID

Discord|Channel|1264175200535056425

### 错误描述

执行\~wiki set设置页面的时候可能会被吞

### 复现方法

1 执行\~wiki set https://zh.m.wikipedia.org/w
2 执行\~wiki，后面随便跟一个
3 发现其返回的页面链接为 https://zh.m.wikipedia.org/xxxxx

### 本应发生的结果

链接应为 https://zh.m.wikipedia.org/xxxxx

### 备注

链接后 xxxxx 仅比喻

**Comment by zwz211123** [comment]
不知道啥原因，波浪线被吞变成删除的，自己凑合着看吧

**Comment by zwz211123** [comment]
波浪线变成删除了 所以可能不是那么直观

**Comment by DoroWolf** [comment]
没看懂
