### ISSUE TITLE
机器人无法获取用户通过NTQQ发送的图片信息

### ISSUE THREAD

**Issue by DoroWolf** [Teahouse-Studios/akari-bot#1242]
这个Issue虽然很大可能won't fix，还是有必要记录一下
机器人无法获取域名为`https://multimedia.nt.qq.com.cn`的多媒体文件，原因未知

错误信息：
RetryError[<Future at 0x7813f1353590 state=finished raised AttributeError>]

这个问题在QQ以外的平台不会出现

**Comment by SilianZ** [comment]
参考文档：
https://gitee.com/xiaoye12123/ws-plugin/issues/I9J5P5
https://blog.csdn.net/weixin_43107613/article/details/115764212
https://github.com/whitechi73/OpenShamrock/issues/236

**Comment by SilianZ** [comment]
还有一个问题：
小可不支持获取 Lagrange 发来的图片。

https://github.com/Teahouse-Studios/akari-bot/blob/86aa1dc51c5940c623ae73053663e292c8a5d653/bots/aiocqhttp/message.py#L226-L227

这两行代码影响的。

在其他平台中，图片的消息形式是 `[CQ:image,url={url}]`，而在 Lagrange 里面，消息形式是 `[CQ:image,path={url}]`。

所以需要在此判断是否平台为 Lagrange。

**Comment by SilianZ** [comment]
报错是 `Timeout error`。个人认为原因有两个：

1. aiocqhttp 或小可代码中传入 url 时对字符串的解析出错导致请求出错
2. 新版 NTQQ 的图床问题（`https://multimedia.nt.qq.com.cn`）
3. `rkey` 错误问题

**Comment by DoroWolf** [comment]
> 还有一个问题：
> 
> 小可不支持获取 Lagrange 发来的图片。
> 
> https://github.com/Teahouse-Studios/akari-bot/blob/86aa1dc51c5940c623ae73053663e292c8a5d653/bots/aiocqhttp/message.py#L226-L227
> 
> 这两行代码影响的。
> 
> 在其他平台中，图片的消息形式是 `[CQ:image,url={url}]`，而在 Lagrange 里面，消息形式是 `[CQ:image,path={url}]`。
> 
> 所以需要在此判断是否平台为 Lagrange。
> 
> 对于 Lagrange 的解析代码如下：
> 
> ```python
> if ss.startswith('path='):
>     lst.append(Image(ss[5:-1]))
> ```

Onebot是这样的，协议端只管随便定标准就行了，而框架端要考虑的就很多了

**Comment by DoroWolf** [comment]
破案了
![IMG_20240801_013040](https://github.com/user-attachments/assets/66e94273-57c0-4a75-a674-b5fbbc2da990)
服务端没法传图，只能拍屏了（安详）

**Comment by DoroWolf** [comment]
破案了
![Uploading IMG_20240801_013040.jpg…]()
服务端没法传图，只能拍屏了（安详）

> 破案了 ![IMG_20240801_013040](https://private-user-images.githubusercontent.com/61273857/353928462-66e94273-57c0-4a75-a674-b5fbbc2da990.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0NDc2MTcsIm5iZiI6MTcyMjQ0NzMxNywicGF0aCI6Ii82MTI3Mzg1Ny8zNTM5Mjg0NjItNjZlOTQyNzMtNTdjMC00YTc1LWE2NzQtYjVmYmJjMmRhOTkwLmpwZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzMxVDE3MzUxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMGIyZThkYjk0ZjZkMDNhYjQwOWMxNGQ4Y2E2YTRkNDE2M2ZlNTRhMDFhYzk3MWZlZWQ0YWVhYTUwYmEwMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7k2drWlZCNY8dBJqghhsd-wCL6_Lh8oFtMX8qSlyZlI) 服务端没法传图，只能拍屏了（安详）

合理推测是-1切片的锅，预计是拿来去除最后的右中括号的
