### ISSUE TITLE
[BUG]: `emojimix` 模块运行超时

### ISSUE THREAD

**Issue by youzi-2333** [Teahouse-Studios/akari-bot#1247]
### 开始之前……

- [X] 我已在 [Issue](https://github.com/Teahouse-Studios/bot/issues) 中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法。

### 聊天平台

QQ 群

### 用户 ID

QQ|2934348842

### 对话 ID

QQ|Group|379026872

### 错误信息

```
执行命令时发生错误：
RetryError[<Future at 0x7f0389ecfd10 state=finished raised TimeoutError>]
此问题可能因机器人未及时处理消息导致，若反复发生，请将此消息报告给机器人开发者。
错误汇报地址：https://s.wd-ljt.com/botreportbug
```

### 错误描述

执行 `~emojimix 🤬 😀`。

### 复现方法

1. 执行 `~emojimix 🤬 😀`
2. 第一次：成功返回结果；
3. 第二次：失败，出现以上报错信息。

### 本应发生的结果

应成功返回结果。

### 截图

[image1](https://github.com/user-attachments/assets/40a5be2d-ecaf-428f-81db-ffb51d4062e6)
[image2](https://github.com/user-attachments/assets/6a977fbd-baf1-40de-af9f-dac39ecf0432)
[image3](https://github.com/user-attachments/assets/1e2329b6-cf95-430d-8f4a-1c79a8fb53b2)

### 备注

检索式：`emojifix`。

感谢！

**Comment by DoroWolf** [comment]
可能为服务器带宽问题，导致偶尔请求超时
此问题无法通过debug修复，请理解

**Comment by youzi-2333** [comment]
那能不能把这个命令导致的 `TimeoutError` 的报错信息加一句 `可能是带宽相关问题，请过几分钟再试` 防止别人再跑来交反馈（

或者我重新交一个 issue？

**Comment by DoroWolf** [comment]
> 那能不能把这个命令导致的 `TimeoutError` 的报错信息加一句 `可能是带宽相关问题，请过几分钟再试` 防止别人再跑来交反馈（
> 
> 或者我重新交一个 issue？

这个关于TimeoutError的异常信息是专门引出来的，不然每次发生超时错误，开发者群都能收到关于超时的报错信息（说到底还是服务器不给力）

不过提交反馈的部分还是有必要的，尤其是如果服务端彻底寄了的时候（就像报错信息中说的`若反复发生`那样）

反正如果别人因为这个问题提交相同issue的话，关掉加上duplicated标签就够了XD
