### ISSUE TITLE
[FEATURE]: 全局黑名单管理功能实现

### ISSUE THREAD

**Issue by ZoruaFox** [Teahouse-Studios/akari-bot#1277]
### 开始之前……

- [X] 我已在 [Issue](https://github.com/Teahouse-Studios/bot/issues) 中搜索过我的建议，确定没有人提出过此建议。

### 建议描述

添加一个“全局黑名单”功能，在小可拥有管理权限的群内禁言/移除并提示黑名单内成员并显示自行设定的加黑原因，在无权限的群内仅提示。

小可现在的总体偏娱乐功能，所以不知道能不能有机会加入群聊管理相关的功能，辛苦各位开发者。

### 实现方法

内置逻辑

### 接口

内置逻辑

**Comment by DoroWolf** [comment]
与#728重复
