### ISSUE TITLE
取消option类型模块

### ISSUE THREAD

**Issue by OasisAkari** [Teahouse-Studios/akari-bot#128]
1. wiki_fandom_addon归类到toggle命令下，使用~toggle wiki_fandom_addon进行切换
2. SenderInfo下新增一字段用于存储toggle的数据

**Comment by Dianliang233** [comment]
如果要取消 option 类型，那么干脆就把所有模块的配置储存在中央吧

**Comment by Dianliang233** [comment]
*配置：各种设置，比如 `~wiki set`

**Comment by OasisAkari** [comment]
> 如果要取消 option 类型，那么干脆就把所有模块的配置储存在中央吧

这个暂时维持成这样，懒得再把数据挪来挪去了（

**Comment by OasisAkari** [comment]
这个想法目前不是很成熟也没时间写 暂时搁置一段时间

**Comment by Dianliang233** [comment]
或者约定一个子命令 `~cmd option <option_name> <option_value>`

**Comment by OasisAkari** [comment]
toggle 命令用来切换核心级别的参数调整好了

其它模块的参数由其约定的子命令控制，符合直觉操作
