### ISSUE TITLE
[BUG]: github搜索，本应该返回项目摘要图片却出现mime了问题。

### ISSUE THREAD

**Issue by flcwsf** [Teahouse-Studios/akari-bot#1298]
### 开始之前……

- [X] 我已在 [Issue](https://github.com/Teahouse-Studios/bot/issues) 中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法。

### 聊天平台

QQ 群

### 用户 ID

QQ|197722682

### 对话 ID

QQ|Group|687397225

### 错误信息

执行命令时发生错误：
'NoneType' object has no attribute 'mime'
请将此信息报告给机器人开发者。错误汇报地址：
https://s.wd-ljt.com/botreportbug

### 错误描述

我执行了~github Creators-of-Create/Create
中间他人执行了其他指令
随后报错

### 复现方法

执行~github Creators-of-Create/Create
出现了文字回答
他人在获取下一个信息之前执行~coin 10000
出现了抛硬币结果
随后出现了此错误

### 本应发生的结果

本来应该返回项目简介，随后返回摘要图片

### 截图

![Uploading Screenshot_20240829_143129.jpg…]()

**Comment by DoroWolf** [comment]
超时问题，wont fix
issue暂时保留以处理报错提示问题
