### ISSUE TITLE
自动填充在config.toml中不存在的默认options，完善配置注释

### ISSUE THREAD

**Issue by OasisAkari** [Teahouse-Studios/akari-bot#1322]
感觉要人去翻wiki再填还是太麻烦

**Comment by DoroWolf** [comment]
Config()函数中有可自定义的默认值其实（？

**Comment by OasisAkari** [comment]
就是发现config.toml中那个option不存在后，把那个默认值直接填进config.toml里面，不然有可能要翻wiki才可能知道键名之类的
