### ISSUE TITLE
QQ频道机器人（官方）适配TODO

### ISSUE THREAD

**Issue by OasisAkari** [Teahouse-Studios/akari-bot#133]

**Comment by OasisAkari** [comment]
官方频道机器人限制较多，由于仅响应带有@机器人的消息，现行代码需要进行大幅修改。

且上线需要审核，考虑分拆出一个分支用于进行长维护。

**Comment by OasisAkari** [comment]
同时命令可能需要进行中文化以符合标准

**Comment by OasisAkari** [comment]
可能也会适用于明年4月后的discord（？

**Comment by OasisAkari** [comment]
#53会被先提上日程以兼容消息模板

**Comment by OasisAkari** [comment]
此提案可能需要暂时搁置，，，，，都2202年了官方库还不基于async开发，，，我只能表达个对此深切感到遗憾了罢，，，，，

**Comment by OasisAkari** [comment]
支持异步了，彳亍

**Comment by lakejason0** [comment]
yeet步

**Comment by OasisAkari** [comment]
需要一个二级跳转的短链接

**Comment by Dianliang233** [comment]
> 需要一个二级跳转的短链接

已完成：https://github.com/Teahouse-Studios/middleman
