### ISSUE TITLE
[BUG]: twenty_four交互结果有误

### ISSUE THREAD

**Issue by hubbyag** [Teahouse-Studios/akari-bot#1342]
### 开始之前……

- [X] 我已在 [Issue](https://github.com/Teahouse-Studios/bot/issues) 中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法。

### 聊天平台

QQ 群

### 用户 ID

QQ|3109975437

### 对话 ID

QQ|Group|812736312

### 错误描述

给出4个数字，但是使用少于4个数字组成表达式也可以算回答正确。比如给[4,3,4,6]，输出4*6。
（未在本该没有解的情况下尝试过）

### 复现方法

1.如上

### 本应发生的结果

应该输出答案错误/表达式错误

**Comment by DoroWolf** [comment]
算是老bug了，之前也出现过这个问题，也尝试过修复🤔
