### ISSUE TITLE
[NEW]: 加入新群

### ISSUE THREAD

**Issue by skytianle666** [Teahouse-Studios/akari-bot#1406]
### 开始之前……

- [x] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [x] 我是群聊的管理员，或群主或管理员允许机器人入群

### QQ号

1430413773

### QQ群

490665720

### 入群方式

私密群聊，无特殊入群答案，不支持二维码加群，无法通过搜索群号加群，可以通过手动邀请加群，已邀请。

### 群主或管理员同意

我是本群的群主或管理员。

### 备注

谢谢

**Comment by DoroWolf** [comment]
未搜索到群聊
