### ISSUE TITLE
[NEW]: 加入新群

### ISSUE THREAD

**Issue by Ext1nguisher** [Teahouse-Studios/akari-bot#1476]
### 开始之前……

- [x] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [x] 我是群聊的管理员，或群主或管理员允许机器人入群

### QQ号

3372728115

### QQ群

528485004

### 入群方式

本群没有入群方式，就我和我几个朋友。不支持任何方式的加群邀请（除我本人邀请）。
点击链接加入群聊【1】：<已屏蔽>

### 群主或管理员同意

我是本群的群主或管理员。

**Comment by OasisAkari** [comment]
请提供一个二维码或者加群链接，待处理完毕后我们会删除这些信息。

**Comment by Ext1nguisher** [comment]
> 请提供一个二维码或者加群链接，待处理完毕后我们会删除这些信息。

已提供，感谢提醒，道歉哈。

**Comment by OasisAkari** [comment]
申请已发送，抱歉没看到提醒
