### ISSUE TITLE
[BUG]: Bot发的帮助图似乎该改改？

### ISSUE THREAD

**Issue by z0z0r4** [Teahouse-Studios/akari-bot#176]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法

### 聊天平台

QQ群

### 用户ID

3531890582

### 群组ID

私聊bot

### 错误信息

似乎server模块-p参数无法显示玩家信息
来源与bot发的帮助图，~help时
wiki上没有关于-r 和 -p的信息？-r大概还可用
大概其中有一些东西是得修改了
![Screenshot_20220121_221614](https://user-images.githubusercontent.com/78744121/150542691-6f317039-f9a2-49b7-9e78-fcb7a1ad0a37.jpg)
![-7c4fb23478723015](https://user-images.githubusercontent.com/78744121/150542735-6d01d6a5-aba9-4cd2-bef4-4a62847cca3d.jpg)

### 错误描述

~help

### 复现方法

~help
~server ip -p

### 本应发生的结果

返回玩家信息

### 截图

在上面

**Comment by OasisAkari** [comment]
后面再看看

**Comment by z0z0r4** [comment]
顺便多来个bug
![Screenshot_20220122_002622](https://user-images.githubusercontent.com/78744121/150563410-9ea99115-4b26-4e97-8ce3-92271c02bf85.jpg)
迷惑…

**Comment by HornCopper** [comment]
这个在go-cq端的显示可能就是“群消息发送失败，账号可能被风控”

**Comment by OasisAkari** [comment]
属于账号被风控 无法解决

发出的某个字段会被tx风控 导致无法发出 然后导致报错

**Comment by OasisAkari** [comment]
属于是服务器端返回的motd的问题，与机器人无关
