### ISSUE TITLE
增加使用统计

### ISSUE THREAD

**Issue by Dianliang233** [Teahouse-Studios/akari-bot#225]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

统计机器人的使用情况。目前能想到的：

- 模块/命令和子命令使用频率
- 群使用统计

**Comment by OasisAkari** [comment]
备忘：
需要仿照nonebot，实现一个MessageSession.finish参数，用来终结会话以便进行实际调用统计

实现过程并不难，在core.elements.message.MessageSession中新建一个finish函数，用来发送消息后raise一个FinishedException（定义于core.exceptions），然后core.parser.message中catch这个FinishedException再写相关的统计操作

然后需要对每个模块进行相应更改
