### ISSUE TITLE
重写命令解析

### ISSUE THREAD

**Issue by OasisAkari** [Teahouse-Studios/akari-bot#251]
需要支持的特性

1. 现有特性基础支持
2. 命令优先级支持
3. 函数强绑定

可能支持的其他特性
1. 命令入参
Example:
```python

command = on_command('xxx')

@command.handle('<arg1> <arg2>')
async def _(msg: MessageSession, arg1, arg2): <- here
    ...

```

**Comment by Dianliang233** [comment]
命令入参感觉还是太麻烦了，需要处理 `abc (aaaa <a>|bbbb <a> <b>) <c>` 这种 edge case，且没有很大的用处，建议不动

**Comment by OasisAkari** [comment]
此次更改后需要注意：
若存在单个装饰器解析多条子命令的情况，则解析器不会自动补全匹配到的命令以外的命令的参数
为此，需要对存在此情况的命令做出以下更改：
`xxx = msg.parsed_msg[<xxx>]` -> `xxx = msg.parsed_msg.get('<xxx>', 缺省值)` 或 `'<xxx>' in msg.parsed_msg`
