### ISSUE TITLE
[NEW]: 机器人入群申请

### ISSUE THREAD

**Issue by cokeenet** [Teahouse-Studios/akari-bot#266]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)

### QQ群组类型

QQ群

### QQ号

3289640025

### QQ群

860912500

**Comment by OasisAkari** [comment]
无法搜索到群聊，请检查入群设置，或提供二维码等方式入群

**Comment by cokeenet** [comment]
[https://s1.328888.xyz/2022/06/18/0IqjM.jpg](url)
谢谢🙏🏼

**Comment by Dianliang233** [comment]
注：入群信息已删除
