### ISSUE TITLE
[BUG]: 

### ISSUE THREAD

**Issue by beiyaohhhc** [Teahouse-Studios/akari-bot#274]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法

### 聊天平台

QQ群

### 用户ID

QQ 2383615282

### 群组ID

QQ752152397

### 错误信息

发生错误：执行命令时发生错误，请报告机器人开发者：
Attempt to access request outside of a relevant context
错误汇报地址：https://github.com/Teahouse-Studios/bot/issues/new?assignees=OasisAkari&labels=bug&template=report_bug.yaml&title=%5BBUG%5D%3A+

### 错误描述

我正在执行~module enable all 接着进行了报错

### 复现方法

1执行~module enable all
2报错

### 本应发生的结果

成功：打开模块“mcplayer”
成功：打开模块“chemical_code”
成功：打开模块“mcv”
成功：打开模块“mcbv”
成功：打开模块“mcdv”
成功：打开模块“mcev”
成功：打开模块“mcmod”
成功：打开模块“maimai”
成功：打开模块“maimai_random_music_regex1”
成功：打开模块“maimai_random_music_regex2”
成功：打开模块“maimai_search_music_regex”
成功：打开模块“maimai_query_chart_regex”
成功：打开模块“maimai_find_song_regex”
成功：打开模块“minecraft_news”
成功：打开模块“feedback_news”
成功：打开模块“mod_dl”
成功：打开模块“cytoid”
成功：打开模块“github”
成功：打开模块“err”
成功：打开模块“weekly”
成功：打开模块“ptt”
成功：打开模块“mcv_rss”
成功：打开模块“mcbv_rss”
成功：打开模块“mcv_jira_rss”
成功：打开模块“mcbv_jira_rss”
成功：打开模块“mcdv_jira_rss”
成功：打开模块“mcbbs_news”
成功：打开模块“wiki”
成功：打开模块“wiki_fandom_addon”
成功：打开模块“wiki_inline”
成功：打开模块“rc”
成功：打开模块“ab”
成功：打开模块“newbie”
成功：打开模块“user”
成功：打开模块“arcaea”
成功：打开模块“bug”
成功：打开模块“bug_regex”
成功：打开模块“idlist”
成功：打开模块“server_disable_revoke”
成功：打开模块“server”
成功：打开模块“meme”
成功：打开模块“weekly_rss”
成功：打开模块“teahouse_weekly_rss”

### 截图

``

**Comment by OasisAkari** [comment]
https://github.com/Teahouse-Studios/akari-bot/blob/master/DEPLOY.md#qqattempt-to-access-request-outside-of-a-relevant-context
