### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by kuriko114514** [Teahouse-Studios/akari-bot#282]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)

### QQ群组类型

QQ群

### QQ号

1433528923

### QQ群

578616565

### 备注

小可快进来~

**Comment by OasisAkari** [comment]
无法搜索到群聊，请提供二维码或邀请链接方式入群，或是检查入群设置

**Comment by kuriko114514** [comment]
> 无法搜索到群聊，请提供二维码或邀请链接方式入群，或是检查入群设置



> 无法搜索到群聊，请提供二维码或邀请链接方式入群，或是检查入群设置

点击链接加入群聊【SXK BE】：https://jq.qq.com/?_wv=1027&k=f8HTzJil

**Comment by Dianliang233** [comment]
注：加群信息已删除
