### ISSUE TITLE
[NEW]: 申请加入群

### ISSUE THREAD

**Issue by XieXiLin3** [Teahouse-Studios/akari-bot#286]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)

### QQ群组类型

QQ群

### QQ号

3068342155

### QQ群

326434334

### 备注

答案：89

**Comment by OasisAkari** [comment]
申请者不属于群聊管理员，请发送一张群主或管理员允许机器人入群的证明截图

**Comment by XieXiLin3** [comment]
![-69fbc09ae19c9a87](https://user-images.githubusercontent.com/55585872/178746999-314ef3d9-79ce-4226-a715-84ff77bc4fc3.png)
