### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by ZhuRuoLing** [Teahouse-Studios/akari-bot#290]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/)

### QQ群组类型

QQ群

### QQ号

3489382552

### QQ群

805091193

**Comment by OasisAkari** [comment]
申请已发送，请检查入群通知，若无请检查是否被过滤。如仍然找不到对应的记录请在本issue下继续回复
