### ISSUE TITLE
[FEATURE]: 发送特定语句回复对应结果

### ISSUE THREAD

**Issue by DoroWolf** [Teahouse-Studios/akari-bot#310]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

希望能做出一个当检测聊天记录中特定的发言时，发送特定发言的模块

如果可以，希望能做使用回复和不使用回复的效果

**Comment by OasisAkari** [comment]
安全性堪忧

**Comment by OasisAkari** [comment]
相当于变相提供echo的权限，出于内容安全原因，不会引入此特性
