### ISSUE TITLE
[FEATURE]: arc性歌功能

### ISSUE THREAD

**Issue by DoroWolf** [Teahouse-Studios/akari-bot#317]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

建议加入arc性歌列表功能，
将1fAar、1lost和1far 1lost的曲目列出

**Comment by DoroWolf** [comment]
可以用~arcaea choke
（choke指性歌）

**Comment by OasisAkari** [comment]
这个要自己魔改botarcapi 目前还不知道要怎么搞
