### ISSUE TITLE
统计数据插入前需检查触发命令的文本合法性

### ISSUE THREAD

**Issue by OasisAkari** [Teahouse-Studios/akari-bot#319]
已知用户输入颜文字将导致统计数据插入报错

**Comment by Dianliang233** [comment]
检查一下数据库用的什么编码。。。。

**Comment by OasisAkari** [comment]
> 检查一下数据库用的什么编码。。。。

utf8捏

**Comment by OasisAkari** [comment]
更改为utf8mb4后解决

**Comment by Dianliang233** [comment]
笨

**Comment by lakejason0** [comment]
谁笨

**Comment by OasisAkari** [comment]
555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555555
