### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by newTechAccount** [Teahouse-Studios/akari-bot#321]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)
- [x] 我是群聊的管理员，或群主或管理员允许机器人入群

### QQ群组类型

QQ群

### QQ号

6765560

### QQ群

624555267

### 入群方式

本群无特殊入群答案，支持搜索群号加群，无需二维码或入群链接。

### 群主或管理员同意

我是本群的群主或管理员。

**Comment by Dianliang233** [comment]
申请已发送

**Comment by newTechAccount** [comment]
是加群申请吗？好像没有

**Comment by OasisAkari** [comment]
> 是加群申请吗？好像没有

已过滤的日志也检查了吗

**Comment by newTechAccount** [comment]
> 

检查了，确定是没有

**Comment by OasisAkari** [comment]
> > 
> 
> 检查了，确定是没有

现在呢

**Comment by newTechAccount** [comment]
还是没有

**Comment by lakejason0** [comment]
检查一下风控？

**Comment by OasisAkari** [comment]
晚点再发送一次看看，也许机器人的账号受到了入群风控

**Comment by newTechAccount** [comment]
怎么检查？

**Comment by lakejason0** [comment]
手机查看群通知，可能会有多个标签，都看看有没有，tx会风控也没办法

**Comment by newTechAccount** [comment]
再次确认没有收到任何消息，包括已过滤部分。

**Comment by lakejason0** [comment]
那就是tx抽风了 :shrug:

**Comment by newTechAccount** [comment]
搞不懂tx。他们完全可以跟钉钉飞书那样开发官方接口，非要这么折腾

**Comment by lakejason0** [comment]
QQ频道：你好

**Comment by lakejason0** [comment]
由于本issue的留言会转发到制作团队相关的群内导致刷屏，以下不再回复

**Comment by Dianliang233** [comment]
都可以说 有什么不能说的

**Comment by newTechAccount** [comment]
还是没有。此刻进群方式已调整为允许任何人加群

**Comment by newTechAccount** [comment]
现在有了，小可3号
