### ISSUE TITLE
[NEW]: 加入新群

### ISSUE THREAD

**Issue by YangHaoNing-temp** [Teahouse-Studios/akari-bot#330]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)
- [x] 我是群聊的管理员，或群主或管理员允许机器人入群

### QQ群组类型

QQ群

### QQ号

3476809262

### QQ群

626348038

### 入群方式

本群无特殊入群答案，支持搜索群号加群，无需二维码或入群链接。

### 群主或管理员同意

我是本群的群主或管理员。

**Comment by OasisAkari** [comment]
请尝试将入群设置改为直接入群，或是答案入群

**Comment by YangHaoNing-temp** [comment]
已修改

**Comment by OasisAkari** [comment]
> 已修改
> 

不能设置为需要管理员同意的，机器人账号被风控了，管理员收不到消息

**Comment by YangHaoNing-temp** [comment]
![image](https://user-images.githubusercontent.com/83169812/185780331-1a1e687f-620f-4329-b890-29716c0a3fff.png)
