### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by HreatCenter** [Teahouse-Studios/akari-bot#331]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)
- [x] 我是群聊的管理员，或群主或管理员允许机器人入群

### QQ群组类型

QQ群

### QQ号

2855848316

### QQ群

924411105

### 入群方式

苦力怕论坛

### 群主或管理员同意

我是本群的群主或管理员。

**Comment by OasisAkari** [comment]
申请已发送，若未收到请在此处回复
