### ISSUE TITLE
[NEW]: 加入新群

### ISSUE THREAD

**Issue by JesKi13567** [Teahouse-Studios/akari-bot#357]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)
- [X] 我是群聊的管理员，或群主或管理员允许机器人入群

### QQ群组类型

QQ群

### QQ号

772000672

### QQ群

756538722

### 入群方式

入群答案填写 小可 就好

### 群主或管理员同意

我是本群的群主。

**Comment by OasisAkari** [comment]
申请已发送，若未收到请在此issue下回复
