### ISSUE TITLE
[APPEAL]: 封禁申诉

### ISSUE THREAD

**Issue by salty-breads** [Teahouse-Studios/akari-bot#384]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)
- [X] 我确定这是机器人误判而造成的封禁。

### 聊天平台

QQ群

### 用户ID

3365676887

### 群组ID

718392712

### 警告次数

1

### 证据

【潜水】小谷同学 16:57:12
~ping

【管理员】小可三号机 16:57:12
小谷同学  
~ping
Pong!

【潜水】小谷同学 16:57:17
~ping

【管理员】小可三号机 16:57:18
小谷同学  
~ping
Pong!

【潜水】小谷同学 16:57:22
~ping

【管理员】小可三号机 16:57:23
小谷同学  
~ping
Pong!

【潜水】Minecraft绿宝石 16:57:28
~meme 沈阳大街

【管理员】小可三号机 16:57:29
Minecraft绿宝石  
~meme 沈阳大街
您有命令正在执行，请稍后再试。

【潜水】小谷同学 16:57:37
~pong

【潜水】小谷同学 16:57:44
~ping

【管理员】小可三号机 16:57:45
小谷同学  
~ping
Pong!

【潜水】小谷同学 16:57:46
~ping

【管理员】小可三号机 16:57:47
小谷同学  
~ping
Pong!

【潜水】小谷同学 16:57:51
~ping

【管理员】小可三号机 16:57:52
小谷同学  
~ping
Pong!

【潜水】小谷同学 16:57:55
~ping

【管理员】小可三号机 16:57:56
小谷同学  
~ping
Pong!

【潜水】小谷同学 16:57:56
~ping

【管理员】小可三号机 16:57:57
小谷同学  
~ping
Pong!

【潜水】小谷同学 16:57:56
~ping

【管理员】小可三号机 16:57:57
小谷同学  
~ping
Pong!

【潜水】小谷同学 16:57:57
~ping

【管理员】小可三号机 16:57:58
小谷同学  
~ping
Pong!

【潜水】小谷同学 16:57:58
~ping

【管理员】小可三号机 16:57:59
小谷同学  
~ping
Pong!

【潜水】小谷同学 16:57:59
~ping

【管理员】小可三号机 16:58:00
小谷同学  
~ping
警告：
根据服务条款，你已违反我们的行为准则。
具体原因：一段时间内使用相同命令的次数过多
这是对你的第1次警告。如超过5次警告，我们将会把你的账户加入黑名单。
如果你有任何异议，请至https://github.com/Teahouse-Studios/bot/issues/new/choose发起issue。

### 备注

我都不知道有这个发多次被警告
而且这10次都没有

**Comment by DoroWolf** [comment]
參見[此處](https://bot.teahouse.team/wiki/%E6%BB%A5%E7%94%A8%E8%AD%A6%E5%91%8A) 。
此為使用命令過多時的正常警告，不接受處理。
