### ISSUE TITLE
[BUG]: meme模块好像出现了问题

### ISSUE THREAD

**Issue by cloudw233** [Teahouse-Studios/akari-bot#397]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法

### 聊天平台

QQ群

### 用户ID

自建的小可bot

### 群组ID

自建的小可bot

### 错误信息

发生错误：执行命令时发生错误，请报告机器人开发者：
unsupported operand type(s) for +: 'NoneType' and 'str'
错误汇报地址： 
https://github.com/Teahouse-Studios/bot/issues/new?assignees=OasisAkari&labels=bug&template=report_bug.yaml&title=%5BBUG%5D%3A+

### 错误描述

执行~meme 金坷垃（也许其他也会，比如nerd也发生了）时发生

### 复现方法

1. 执行”~meme 金坷垃“
2. 报错
3. 执行"~meme Nerd"
4. 报错

### 本应发生的结果

返回从萌娘百科等平台搜索到的内容

**Comment by OasisAkari** [comment]
自建的话需要配置好webrender才能正常工作

**Comment by cloudw233** [comment]
> 自建的话需要配置好webrender才能正常工作

明白了，谢谢
