### ISSUE TITLE
[FEATURE]: 机器人主人发出的加群申请自动通过

### ISSUE THREAD

**Issue by cloudw233** [Teahouse-Studios/akari-bot#401]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

在bot主人给bot发入群邀请的时候自动同意

### 实现方法

- 直接同意入群邀请
- 主人向bot发送类似~join <群号>加群

### 接口

没有哦

**Comment by OasisAkari** [comment]
由于go-cqhttp限制了主动加群，2没有办法实现

**Comment by OasisAkari** [comment]
1已实现，同步至最新commit即可

superuser用户邀请机器人将自动同意入群
