### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by lim040718** [Teahouse-Studios/akari-bot#409]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)
- [X] 我是群聊的管理员，或群主或管理员允许机器人入群

### QQ群组类型

QQ群

### QQ号

1813869568

### QQ群

655026004

### 入群方式

Clannad,AIR,KANON

### 群主或管理员同意

我是本群的群主或管理员。

**Comment by lim040718** [comment]
需要什么吗？

**Comment by OasisAkari** [comment]
> 需要什么吗？

什么需要什么

**Comment by lim040718** [comment]
机器人相关的，还不太了解功能，或者相关规定




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年1月17日(星期二) 晚上8:43
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Teahouse-Studios/akari-bot] [NEW]:  (Issue #409)





  
需要什么吗？
  
什么需要什么？

**Comment by OasisAkari** [comment]
https://bot.teahouse.team/wiki/%E5%BC%80%E5%A7%8B
