### ISSUE TITLE
[FEATURE]: 让群内某一个人无法使用小可

### ISSUE THREAD

**Issue by cloudw233** [Teahouse-Studios/akari-bot#418]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

建议增加让群内某一个人无法使用~help等一系列小可指令的功能

### 实现方法

~ban <id> （例：~ban QQ|114514）

### 接口

无

**Comment by Dianliang233** [comment]
可以，我想个更好的名字

**Comment by OasisAkari** [comment]
~admin ban <UserID>
~admin unban <UserID>
