### ISSUE TITLE
[BUG]: 帮助文档的poetry

### ISSUE THREAD

**Issue by cloudw233** [Teahouse-Studios/akari-bot#435]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法

### 聊天平台

所有平台均有此问题

### 用户ID

none

### 群组ID

none

### 错误信息

none

### 错误描述

自搭建文档写使用poetry管理依赖，但是最新release并没有poetry，是否保留pip install -r requirement.txt的依赖安装方式

### 复现方法

无

### 本应发生的结果

无

**Comment by OasisAkari** [comment]
那就地发一个release好了）
