### ISSUE TITLE
无法加载依赖

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#447]
已使用Poetry安装了所有依赖，由于没有WSL环境，直接在子文件夹输入了poetry install。但是Python无法识别到库。

**Comment by OasisAkari** [comment]
尝试使用poetry shell命令切换环境

**Comment by SilianZ** [comment]
![image](https://user-images.githubusercontent.com/113701655/219046984-cbb0ce00-d812-48f0-92b6-c42e122550be.png)
