### ISSUE TITLE
[Re: #447无法加载依赖]

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#450]
以下是报错截图
![image](https://user-images.githubusercontent.com/113701655/219047416-c2c390b1-fb04-45e7-94d9-47b5a7579dba.png)
尝试使用了`poetry shell`还是无法识别到库
安装时使用的命令是
```powershell 
(Invoke-WebRequest -Uri "https://install.python-poetry.org" -UseBasicParsing).Content | py -
```
无法辨别是从WS下载的还是官网下载的

**Comment by OasisAkari** [comment]
截一下使用`poetry shell`命令之后的输出

**Comment by OasisAkari** [comment]
set-executionpolicy remotesigned
