### ISSUE TITLE
[Re: #450 [Re: #477 无法加载依赖]]

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#452]
![image](https://user-images.githubusercontent.com/113701655/219385717-33118df9-dc2f-4eab-8683-685c9ddd8dc9.png)
试过了，还是不行。

**Comment by SilianZ** [comment]
为什么我使用 `poetry run python console.py` 反而可以

**Comment by OasisAkari** [comment]
检查系统环境变量是否存在多个不同版本的python executable path造成环境冲突的情况

**Comment by OasisAkari** [comment]
安装poetry前请**务必**检查系统环境变量中是否存在多个python executable path并及时清除，否则安装poetry后将会出现python环境混乱导致无法正常加载依赖的情况
