### ISSUE TITLE
[FEATURE]: QQ侧允许接收来自其他设备发送的自身消息

### ISSUE THREAD

**Issue by cloudw233** [Teahouse-Studios/akari-bot#457]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

小可可通过发送消息自我操控（

### 实现方法

bzd

### 接口

bzd

**Comment by cloudw233** [comment]
以小可自身发送的指令是否能默认为superuser执行？

**Comment by OasisAkari** [comment]
现已支持自身消息上报处理。

通过设置go-cqhttp允许自身消息上报后在小可的配置文件中加入`qq_enable_listening_self_message = True` 即可实现处理自己的消息

将bot的账号设置为superuser用户即可实现调用su命令

注意：由于无法区分消息设备来源，有几率出现机器人命令调用被反复解析造成死循环的现象，请谨慎开启此功能。
