### ISSUE TITLE
[FEATURE]: 更好的dice和coin

### ISSUE THREAD

**Issue by DoroWolf** [Teahouse-Studios/akari-bot#459]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

目前的``~coin``与``~dice``命令基于``random``模块使用，但仍然有局限性。
建议加入多个硬币/骰子的同时投掷，以及使用多面体骰子。
不加入参数则默认投掷1个硬币/1个d6骰子。

建议硬币的概率为：正面49.75%，背面49.75%，立起0.5%。
建议的多面骰子：d4，d6，d8，d12，d20。骰子所有面概率均等。

硬币示例：
- ~coin
 - 正面朝上/反面朝上/立起
- ~coin 100
 - 48枚正面朝上，51枚方面朝上，1枚立起
 
骰子示例：
- ~dice
 - 6点
- ~dice d12
 - 12点
- ~dice 60
 - 1点：10个，2点：9个，3点：12个，4点：8个，5点：12个，6点：9个，共210点
- ~dice 40d4
 - 1点：13个，2点：8个，3点：12个，4点：7个，共93点

可选功能：
- 非常用的异形骰子
- 不同种类与数量的多面骰子混合投掷

**Comment by Light-Beacon** [comment]
dice我做了：#415（用法一会在pr下边补一下
