### ISSUE TITLE
连不上……

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#460]
![image](https://user-images.githubusercontent.com/113701655/219778735-28a4e208-7da9-4596-b344-eeb55278884a.png)
![image](https://user-images.githubusercontent.com/113701655/219778801-d1bd14c8-c440-4828-915d-379c11ed263f.png)
![image](https://user-images.githubusercontent.com/113701655/219778888-cae8e19e-5a8a-489e-8b68-51bee0e3188f.png)

**Comment by OasisAkari** [comment]
你开的是console.py，不是bot.py
