### ISSUE TITLE
[FEATURE]: Add something new at DEPLOY.md

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#463]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

完善[自搭建](https://github.com/Teahouse-Studios/akari-bot/blob/master/DEPLOY.md)的一些信息。

### 实现方法

+ 有些命令比如：
```sh
$ poetry install
```

```sh
$ pip install -r requirements.txt
```

需要在WSL环境下才能运行，建议在后面加上如 “WSL的配置方法” 或者 “非WSL环境命令” 的相关内容

+ 完善 `配置平台机器人` 栏目的部分内容，`QQ`：建议写明需要 `另外安装第三方客户端`
+ 通过往部分板块加上部分注释（常见问题等）使自搭建说明更容易阅读
+ 添加 `常见问题` 部分，便于用户进行自搭建，可参考部分issue

**Comment by Dianliang233** [comment]
可是这两个命令不需要wsl就能运行

**Comment by SilianZ** [comment]
```cmd
C:\Users\silia>$ poetry install
'$' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
```
e?

**Comment by lakejason0** [comment]
如果连‘$’和‘#’都不知道只是单纯的命令提示符而不是命令的一部分，那我觉得你可能确实需要学习一下命令行（？）
（不是刻薄，但是你确实需要）

**Comment by SilianZ** [comment]
我的问题，但其他的有关配置的信息确实需要完善一下。

发件人: ***@***.***>
发送时间: 2023年2月19日 10:02
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [Teahouse-Studios/akari-bot] [FEATURE]: Add something new at DEPLOY.md (Issue #463)


如果连‘$’和‘#’都不知道只是单纯的命令提示符而不是命令的一部分，那我觉得你可能确实需要学习一下命令行（？）
（不是刻薄，但是你确实需要）

―

**Comment by Dianliang233** [comment]
若有请直接pr
