### ISSUE TITLE
[FEATURE]: 命令频率限制

### ISSUE THREAD

**Issue by cloudw233** [Teahouse-Studios/akari-bot#473]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

添加命令频率限制功能，为每个群设置命令频率，默认为0（无限制），每秒x条

**Comment by DoroWolf** [comment]
机器人自身拥有滥用警告功能。
若您使用QQ频道或discord，可以自行配置频率限制。

**Comment by cloudw233** [comment]
> 机器人自身拥有滥用警告功能。 若您使用QQ频道或discord，可以自行配置频率限制。

QQ群呢？

**Comment by OasisAkari** [comment]
小可目前通过一些内置函数控制命令滥用次数，可配置`enable_tos=True`来打开（注意：会同时打开其它滥用判定），具体表现为5分钟内同时使用10次相同命令或20次不同的命令，警告消息可在 `core.tos` 中修改。

暂时没有主动控制命令使用次数的功能，后续可实现
