### ISSUE TITLE
[Help]：命令cooldown

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#474]
我现在在一个qq群里面配置了小可，但是我想要某些命令有使用冷却时间，请问有什么解决方案

**Comment by OasisAkari** [comment]
小可目前通过一些内置函数控制命令滥用次数，可配置`enable_tos=True`来打开（注意：会同时打开其它滥用判定），具体表现为5分钟内同时使用10次相同命令或20次不同的命令便警告一次，警告五次即加入黑名单（不再响应对象的任何消息）。警告消息可在 `core.tos` 中修改。

暂时没有主动控制命令使用次数的功能，后续可实现，与 #473 重复所以此issue关闭
