### ISSUE TITLE
[FEATURE]: Osu!bot功能

### ISSUE THREAD

**Issue by cloudw233** [Teahouse-Studios/akari-bot#476]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

如题（

**Comment by OasisAkari** [comment]
添加新功能要求请写清具体需要实现的功能，以及最好提供有关的实现以及api文档等接口，只有几个字的要求除非是我本人需要不然基本上不会实现（因为不是我自己的需求）

**Comment by cloudw233** [comment]
pypi上有相关库，我写不明白所以来发issue（

**Comment by xiaoniaoawa** [comment]
> 添加新功能要求请写清具体需要实现的功能，以及最好提供有关的实现以及api文档等接口，只有几个字的要求除非是我本人需要不然基本上不会实现（因为不是我自己的需求）

人话：查用户信息（如隔壁yunzai查原神一样）
