### ISSUE TITLE
[NEW]: 加入新群

### ISSUE THREAD

**Issue by xunhaii** [Teahouse-Studios/akari-bot#496]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)
- [x] 我是群聊的管理员，或群主或管理员允许机器人入群

### QQ群组类型

QQ群

### QQ号

1774843122

### QQ群

850347853

### 入群方式

本群无特殊入群答案，支持搜索群号加群，无需二维码或入群链接。

### 群主或管理员同意

我是本群的群主或管理员。

**Comment by OasisAkari** [comment]
申请已经发送，若未收到请回复本issue

**Comment by xunhaii** [comment]
> 申请已经发送，若未收到请回复本issue

我并未收到入群申请

**Comment by OasisAkari** [comment]
> > 申请已经发送，若未收到请回复本issue
> 
> 我并未收到入群申请

检查过滤消息，如果依然没有，尝试将入群申请暂时改为正确答案直接入群或无需任何答案入群

**Comment by xunhaii** [comment]
> > > 申请已经发送，若未收到请回复本issue
> > 
> > 
> > 我并未收到入群申请
> 
> 检查过滤消息，如果依然没有，尝试将入群申请暂时改为正确答案直接入群或无需任何答案入群

已改成"允许任何人加群"，现在麻烦再申请一次，谢谢！

**Comment by OasisAkari** [comment]
> 已改成"允许任何人加群"，现在麻烦再申请一次，谢谢！

申请已再次发送，如果还是未收到，需要把管理员审核的限制关闭（bot不知道为什么经常加不上群只能这样，抱歉）
