### ISSUE TITLE
[NEW]: 申请拉入群聊

### ISSUE THREAD

**Issue by XieXiLin3** [Teahouse-Studios/akari-bot#498]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)
- [X] 我是群聊的管理员，或群主或管理员允许机器人入群

### QQ群组类型

QQ群

### QQ号

3068342155

### QQ群

733951376

### 入群方式

本群入群答案是 『落雪无痕LxHTT』，支持搜索群号加群，无需二维码或入群链接。

### 群主或管理员同意

我是本群的管理员。

**Comment by OasisAkari** [comment]
入群答案错误，请检查

**Comment by XieXiLin3** [comment]
> 入群答案错误，请检查

落雪无痕LxHTT
