### ISSUE TITLE
加入新群

### ISSUE THREAD

**Issue by beiyaohhhc** [Teahouse-Studios/akari-bot#501]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)
- [X] 我是群聊的管理员，或群主或管理员允许机器人入群

### QQ群组类型

QQ群

### QQ号

2383615282

### QQ群

824185628

### 入群方式

密码 HFPRO

### 群主或管理员同意

我是本群的管理员。

**Comment by OasisAkari** [comment]
答案错误

**Comment by beiyaohhhc** [comment]
已设置允许任何人加群
