### ISSUE TITLE
[FEATURE]: 考虑加入的一些功能

### ISSUE THREAD

**Issue by DoroWolf** [Teahouse-Studios/akari-bot#518]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

觉得可能需要加入这些功能：
- 转换器
  - [x] 汇率转换
  - [ ] UNIX时间转换
  - [ ] Unicode转换
  - [ ] 二维码生成（可能易被滥用）
  - [ ] Base64编码/解码
  - [x] MD5加密
  - [x] SHA加密
     - [x] SHA1
     - [x] SHA256
     - [x] SHA512
     - [ ] 加盐（可选）
  - [ ] 摩斯电码转换
  - [ ] 繁简转换
    - [ ] 地区词（可选）
  - [ ] 域名whois查询
- 计算器
  - [x] 分解质因数
  - [x] 因式分解
  - [x] 绘制函数图像
  - [x] 化学方程式配平
  - [ ] 文本字数统计

不必全部实现，觉得合适就可实现。

**Comment by Dianliang233** [comment]
ask会支持wolframalpha。

**Comment by z0z0r4** [comment]
看起来 域名whois查询 该 tick 了

**Comment by Dianliang233** [comment]
分解质因数 因式分解 可以用wolfram alpha解决。

**Comment by Dianliang233** [comment]
UNIX时间转换 这个可以做好多文章

时间时区等等可复杂了（（

**Comment by DoroWolf** [comment]
> UNIX时间转换 这个可以做好多文章
> 
> 时间时区等等可复杂了（（

先那先放一下好了
