### ISSUE TITLE
[FEATURE]: mod_dl support modrinth

### ISSUE THREAD

**Issue by z0z0r4** [Teahouse-Studios/akari-bot#526]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

mod_dl support modrinth

### 实现方法

modrinth api

### 接口

https://docs.modrinth.com/

### 备注

正在尝试，没给小可写过module...只用过nb2

**Comment by z0z0r4** [comment]
话说 curseforge 有官方接口为什么不用而用第三方搭建呢？（并不清楚一年前有没有此接口

**Comment by DoroWolf** [comment]
> 话说 curseforge 有官方接口为什么不用而用第三方搭建呢？（并不清楚一年前有没有此接口

这个问题建议问模块原作者 @HornCopper

**Comment by z0z0r4** [comment]
得这周日了...咕唔，又得返校，我会整个的

**Comment by z0z0r4** [comment]
> 得这周日了...咕唔，又得返校，我会整个的

浅问一句，小可所在能顺畅访问外网的吧...？

https://docs.curseforge.com/
https://www.cfwidget.com/

**Comment by HornCopper** [comment]
我写这个的时候并没有官方API，甚至还有CloudFlare阻止访问（

**Comment by z0z0r4** [comment]
> 我写这个的时候并没有官方API，甚至还有CloudFlare阻止访问（

233，已经 rewrite 完了

**Comment by z0z0r4** [comment]
> Reference

https://docs.curseforge.com/#authentication

**Comment by z0z0r4** [comment]
> 我写这个的时候并没有官方API，甚至还有CloudFlare阻止访问（

https://docs.curseforge.com/#authentication

https://mcim.z0z0r4.top//
