### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by pwfwf** [Teahouse-Studios/akari-bot#542]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)
- [X] 我是群聊的管理员，或群主或管理员允许机器人入群

### QQ群组类型

QQ群

### QQ号

2532498755

### QQ群

570718688

### 入群方式

本群无特殊入群答案，支持搜索群号加群，无需二维码或入群链接。

### 群主或管理员同意

我是本群的群主或管理员。

### 备注

谢谢你们的机器人，我想知道自己搭建一个简单的qq机器人是否复杂，或者说能否在小可的模板上进行修改

**Comment by OasisAkari** [comment]
无法搜索到群聊，另：自搭建可以参考这里：https://github.com/Teahouse-Studios/akari-bot/blob/master/DEPLOY.md

编写模块可以参考这个示例：https://github.com/Teahouse-Studios/akari-bot/blob/master/example/new_module/__init__.py

https://bot.teahouse.team/wiki/%E6%96%B0%E5%BB%BA%E6%A8%A1%E5%9D%97%E6%8C%87%E5%8D%97
