### ISSUE TITLE
如何在我的模块中实现i18n？

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#552]
简要说一下做法

**Comment by OasisAkari** [comment]
模块文件夹下新建locales文件夹，然后新建`zh_cn.json`、`zh_tw.json`、`en_us.json`分别存储不同语言的键名（参考其他模块）

然后代码中通过`MessageSession.locale.t("键名")`调用

指令帮助则是 `{键名}`，如`test <arg1> {{help.test}}` （对比非i18n帮助多了一对方括号）
