### ISSUE TITLE
[FEATURE]: 自构建bot如何引入频道支持

### ISSUE THREAD

**Issue by ZoruaFox** [Teahouse-Studios/akari-bot#557]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

如题，小可的官方服务貌似支持QQ频道（beta），但是关于自行构建的相关配置中暂未发现处理频道消息的配置，是否有针对自行构建的bot的频道消息收发支持？

### 实现方法

调用go-cqhttp接口实现处理频道消息

### 接口

https://docs.go-cqhttp.org/api/guild.html#获取频道系统内bot的资料

### 备注

各位大大们开发辛苦了，滑跪一个orz

**Comment by OasisAkari** [comment]
将go-cqhttp使用协议切至支持接收频道消息的即可，比如Android Pad协议

不过由于go-cqhttp对频道消息支持的不完善，频道内消息无法撤回，且频道列表不会自动刷新（加入新频道需要手动重启一次gocqhttp）

**Comment by ZoruaFox** [comment]
> 将go-cqhttp使用协议切至支持接收频道消息的即可，比如Android Pad协议
> 
> 不过由于go-cqhttp对频道消息支持的不完善，频道内消息无法撤回，且频道列表不会自动刷新（加入新频道需要手动重启一次gocqhttp）

了解，我这边的疑惑解决了，感谢大大回复

另外大大有意向在DEPLOY.md相关章节写一个相关章节的说明嘛，如果可以的话我开pr也行（）

**Comment by OasisAkari** [comment]
> > 将go-cqhttp使用协议切至支持接收频道消息的即可，比如Android Pad协议
> > 
> > 不过由于go-cqhttp对频道消息支持的不完善，频道内消息无法撤回，且频道列表不会自动刷新（加入新频道需要手动重启一次gocqhttp）
> 
> 了解，我这边的疑惑解决了，感谢大大回复
> 
> 另外大大有意向在DEPLOY.md相关章节写一个相关章节的说明嘛，如果可以的话我开pr也行（）

可以提pr，我自己写的话可能会忘掉（）
