### ISSUE TITLE
[WEBSITE TUNING]: 关于bot.teahouse.team

### ISSUE THREAD

**Issue by ZoruaFox** [Teahouse-Studios/akari-bot#565]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法

### 聊天平台

所有平台均有此问题

### 用户ID

354746447

### 群组ID

-

### 错误信息

504 Gateway Time-out
OR
High firstPack_time

### 错误描述

**注意，本问题有关于bot.teahouse.team网站，与机器人关联极小。如果本issue发布在了错误的位置，Close as won't fix即可。**
我注意到bot.teahouse.team的网站构建在MediaWiki版本1.39.1上并貌似使用了阿里云CDN做内容分发，但是根据云拨测显示的结果，在99个拨测IP同时对网站的请求、4+3+6的抽样拨测结果来看，在部分情况下仍然出现了请求超时、高首包时间的情况。

全地域与抽样分析出现的超时判断为网站的并发能力貌似不足，所以在这里问问站点的相关缓存策略配置，包括源站的缓存、CDN节点缓存配置的一些问题，甚至如果可以的话，我这边有阿里云DCDN的控制台实例可以帮助CNAME转发，权当为项目赞助了。

如果具体配置（包括源站IP）过于私密不便于在这里透露，上面有我的QQ，大大如果不嫌弃的话可以随时dd我。

### 复现方法

Just access the wiki website by normal network environment and test using disposableTest.

### 本应发生的结果

all 200 OK, lower http request time.

### 截图

![image](https://user-images.githubusercontent.com/96456728/233767191-e3f8931f-b0b6-4878-8d99-51bd44d63a49.png)

### 备注

如果具体配置（包括源站IP）过于私密不便于在这里透露，上面有我的QQ，大大如果不嫌弃的话可以随时dd我。

维护项目不容易，大大辛苦了！

**Comment by z0z0r4** [comment]
![image](https://user-images.githubusercontent.com/78744121/233767593-a81210b4-2662-477d-9c10-1c24d2acc995.png)

人在广东，说实话平时就感到加载很慢，有时不如 cloudflare 了都（

**Comment by ZoruaFox** [comment]
> 人在广东，说实话平时就感到加载很慢，有时不如 cloudflare 了都（

其实如果cloudflare还好，他家专做CDN有一部分的国内线会有一定的加速，但是这个加载慢感觉是出在后端PHP上，跟CDN关联不高，所以在想可能跟网站后端缓存策略有那么一点点问题（？）

**Comment by z0z0r4** [comment]
> > 人在广东，说实话平时就感到加载很慢，有时不如 cloudflare 了都（
> 
> 其实如果cloudflare还好，他家专做CDN有一部分的国内线会有一定的加速，但是这个加载慢感觉是出在后端PHP上，跟CDN关联不高，所以在想可能跟网站后端缓存策略有那么一点点问题（？）

免费有国内线？不得而知...

**Comment by Dianliang233** [comment]
要不要再试试？

**Comment by ZoruaFox** [comment]
用户访问差不多了2333
不过貌似创建新账户出问题了
BTW如果是PHP缓存的话可以试试OPcache，虽然Redis也……没啥问题
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/96456728/233770549-129a665a-5117-4bd9-aa60-a122ff403f4e.png">

以及新拨测结果
<img width="943" alt="image" src="https://user-images.githubusercontent.com/96456728/233770875-0e4a2845-4fde-40ba-8f96-30470f8bf9e4.png">

**Comment by XxLittleCxX** [comment]
opcache 有

**Comment by ZoruaFox** [comment]
$wgMainCacheType 可以memcached，$wgObjectCaches因为cdn有了所以就没搞，至于OPcache是自动调用的，那个建议安装了就不动
以及上面那个Redis的问题（）

**Comment by z0z0r4** [comment]
https://bot.teahouse.team/wiki/%E5%BC%80%E5%A7%8B

![image](https://user-images.githubusercontent.com/78744121/233771431-8bd7eb63-b85e-40e1-a044-c563dc54588e.png)

**Comment by XxLittleCxX** [comment]
还是服务器太烂了（

**Comment by ZoruaFox** [comment]
> 还是服务器太烂了（

MediaWiki要求还不算太高，基本上装几个缓存够用就行
另外IP Whitelist策略把我给挡了 = = 咱DDoS不兴这么防啊（不是）

**Comment by XxLittleCxX** [comment]
我在看 `$wgDebugToolbar`，暂时把我以外的 ip 都 ban 了

**Comment by lakejason0** [comment]
你说得对，但是MediaWiki是一款由维基媒体基金会开发的屎山（下略）（不是）

---
Generated by [koishi-plugin-github](https://github.koishi.chat/).

**Comment by ZoruaFox** [comment]
>

> 我在看 `$wgDebugToolbar`，暂时把我以外的 ip 都 ban 了

成，顺便给孩子打了20r，大大加油（题外话：前不久才知道居然还是梗体中文资源包的开发者，滑跪orz）
