### ISSUE TITLE
[FEATURE]: Bilibili影片解析

### ISSUE THREAD

**Issue by DoroWolf** [Teahouse-Studios/akari-bot#589]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

通过bilibili长网址/短网址/av号/bv号/小程序链接获取bilibili影片的封面、标题、类型、UP主、日期等信息。

### 接口

https://github.com/mengshouer/nonebot_plugin_analysis_bilibili

### 备注

这是从其他机器人中取得的程序，可提供参考：
https://github.com/su226/IdhagnBot/blob/main/plugins/bilibili_link.py

**Comment by z0z0r4** [comment]
有人做吗？如果不急我实现试试看？

https://github.com/Nemo2011/bilibili-api

**Comment by wyapx** [comment]
烂大街功能，建议不实现

**Comment by DoroWolf** [comment]
> 烂大街功能，建议不实现

好好好好好好好好

**Comment by DoroWolf** [comment]
做好了
