### ISSUE TITLE
[MEDIAWIKI ERROR]: 主站多关键元素失效

### ISSUE THREAD

**Issue by ZoruaFox** [Teahouse-Studios/akari-bot#600]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

主页多模板失效，核心原因为缩略图文件丢失
![Screenshot_20230516_143529_com microsoft emmx_edit_72041545699943](https://github.com/Teahouse-Studios/akari-bot/assets/96456728/b33d64c0-6570-4211-a75c-b48ac7d37c79)

### 实现方法

Regenerate the thumb images by uploading original files again.

### 接口

Special:Upload

**Comment by Dianliang233** [comment]
@XxLittleCxX you broke it

**Comment by DoroWolf** [comment]
修好了
