### ISSUE TITLE
[FEATURE]: 新html图片渲染

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#604]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

[nonebot-plugin-htmlrender](https://github.com/kexue-z/nonebot-plugin-htmlrender/)

该渲染器：

- 通过 html 和浏览器生成图片
- 支持`纯文本` `markdown` 和 `jinja2` 模板输入
- 通过 CSS 来控制样式

其他详细说明请查看文档。

代码迁移时请注重开源协议。

### 实现方法

更改部分图片生成时的代码，达到更好使用效果。

### 接口

https://github.com/kexue-z/nonebot-plugin-htmlrender/

**Comment by SilianZ** [comment]
kexue-z/nonebot-plugin-heweather (github.com)<https://github.com/kexue-z/nonebot-plugin-heweather>
这是原作者自产自销的使用案例。

**Comment by Dianliang233** [comment]
> kexue-z/nonebot-plugin-heweather (github.com)<https://github.com/kexue-z/nonebot-plugin-heweather>
> 这是原作者自产自销的使用案例。
> 

我说有什么现在 webrender 不能做到，而这个可以做到的

**Comment by SilianZ** [comment]
少配置一个运行环境，多一个端口。

好像只有这些了吧
