### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by luo2f** [Teahouse-Studios/akari-bot#608]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)
- [X] 我是群组的管理员，或群主或管理员允许机器人入群

### QQ群组类型

QQ频道（beta）

### QQ号

1375880562

### QQ群

https://pd.qq.com/s/flh8ym0e9

### 入群方式

题干：
Cytoid b站官方名称？

答案：
Cytoid_BOT

### 群主或管理员同意

我是本群的群主或管理员。

**Comment by OasisAkari** [comment]
已处理，如频道内无法使用命令请反馈
