### ISSUE TITLE
[BUG]: user模块出现问题

### ISSUE THREAD

**Issue by ZoruaFox** [Teahouse-Studios/akari-bot#611]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法

### 聊天平台

QQ群

### 用户ID

354746447

### 群组ID

self-deploy

### 错误信息

日志片段文件见下：
[Untitled-1.log](https://github.com/Teahouse-Studios/akari-bot/files/11522862/Untitled-1.log)
可选：
https://github.com/ZoruaFox/Archives/blob/main/akari-bot%20errorlog.log

### 错误描述

执行~user <username>时发生了非预期的控制台错误，且在附加参数-p时无法生成图片

### 复现方法

1.执行`~user <username> `或者`~user <username> -p`
2.Error occurred.

### 本应发生的结果

Get information with no console errors.

### 截图

<img width="534" alt="image" src="https://github.com/Teahouse-Studios/akari-bot/assets/96456728/bcba3650-5819-4bf7-82d4-ead875fe70fd">

### 备注

本例中的起始wiki为https://wiki.zorua.top/

**Comment by OasisAkari** [comment]
1. 404错误请无视，因为这个模块最初是设计给gamepedia（fandom）使用的，他们的用户页有另外的socialprofile扩展来统计额外的消息

2. 如果你的wiki和bot是架设在同一个服务器上的，那么你可能需要在config文件中加入`allow_request_private_ip = True`来允许访问本地地址，若还是不行请重新提供反馈
