### ISSUE TITLE
[BUG]: chemical_code与twenty_four的交互问题

### ISSUE THREAD

**Issue by DoroWolf** [Teahouse-Studios/akari-bot#646]
同时激活chemical_code和twenty_four会出现不可预料的意外。
- 输入~chemical_code
- 输入~twenty_four
- 随意发言
- chemical_code模块无法正常接收消息

初步判断可能是使用不同函数的冲突问题。

**Comment by DoroWolf** [comment]
未来考虑会将模块的激活方式改为每个群聊一次只能开启一个游戏模块，从而解决此问题

**Comment by OasisAkari** [comment]
当wait系列函数被调用时，函数将会向一个字典中写入本次等待回复的信息，字典的键值与用户id相绑定，导致在多重等待的情况下前一次的调用信息会被后面的调用顶掉，导致你说的问题发生

解决方法要么是重写这一部分的内容使其与id弱相关，要么是阻止这种情况发生

**Comment by DoroWolf** [comment]
考虑将两个模块合并为game模块来解决这个问题

**Comment by Dianliang233** [comment]
> 考虑将两个模块合并为game模块来解决这个问题

不要。应该在bot层面增加一个锁。

**Comment by DoroWolf** [comment]
> > 考虑将两个模块合并为game模块来解决这个问题
> 
> 不要。应该在bot层面增加一个锁。

才看到...凭空加个新功能看着挺费时间😓
目前的状况是共用游戏状态，这样可以事先拦截导致问题的操作

**Comment by DoroWolf** [comment]
（而且重写真的很费力...）

**Comment by Dianliang233** [comment]
> > > 考虑将两个模块合并为game模块来解决这个问题
> > 
> > 不要。应该在bot层面增加一个锁。
> 
> 才看到...凭空加个新功能看着挺费时间😓
> 目前的状况是共用游戏状态，这样可以事先拦截导致问题的操作

并不是的。这不只是这两个游戏，更是整个bot的问题——在一个聊天群组里不应该可以同时有两个命令在等待消息。这样做没有解决问题啊。。。

**Comment by DoroWolf** [comment]
这个时候请致电 @OasisAkari .jpg
暂时先这样解决好了，未来问题解决以后也可以再拆解，这个Issue就先不关闭了

**Comment by DoroWolf** [comment]
> > > > 考虑将两个模块合并为game模块来解决这个问题
> > > 
> > > 
> > > 不要。应该在bot层面增加一个锁。
> > 
> > 
> > 才看到...凭空加个新功能看着挺费时间😓
> > 目前的状况是共用游戏状态，这样可以事先拦截导致问题的操作
> 
> 并不是的。这不只是这两个游戏，更是整个bot的问题——在一个聊天群组里不应该可以同时有两个命令在等待消息。这样做没有解决问题啊。。。

这个时候请致电 @OasisAkari .jpg
暂时先这样解决好了，未来问题解决以后也可以再拆解，这个Issue就先不关闭了

**Comment by Light-Beacon** [comment]
应该给字典设一个标记表示任务是否完成，如果没完成还要加的话直接抛一个异常出来
（不过在发送24点命令的时候居然没判到之前在等待的cc头上？）

**Comment by DoroWolf** [comment]
> 应该给字典设一个标记表示任务是否完成，如果没完成还要加的话直接抛一个异常出来 （不过在发送24点命令的时候居然没判到之前在等待的cc头上？）

目前的策略就是这样的，因为字典没法跨模块😓

**Comment by Light-Beacon** [comment]
> > 应该给字典设一个标记表示任务是否完成，如果没完成还要加的话直接抛一个异常出来 （不过在发送24点命令的时候居然没判到之前在等待的cc头上？）
> 
> 
> 
> 目前的策略就是这样的，因为字典没法跨模块😓

我的意思是这个应该是底层的`MessageTaskManager`干的事，不应该是模块自己搞这个。btw这个异常捕捉应该放在捉到异常然后发送错误消息那个（我不知道那个在哪）在一块

**Comment by OasisAkari** [comment]
理论上此问题已修复，但是chemspider这一会炸了，暂时无法检验

将两个模块恢复回原来的样子即可，不会造成冲突

**Comment by DoroWolf** [comment]
> 理论上此问题已修复，但是chemspider这一会炸了，暂时无法检验
> 
> 将两个模块恢复回原来的样子即可，不会造成冲突

chemspider已恢复。经过检验，问题仍然没有解决。

**Comment by OasisAkari** [comment]
已修复
