### ISSUE TITLE
[FEATURE]: Matrix support

### ISSUE THREAD

**Issue by xtexChooser** [Teahouse-Studios/akari-bot#681]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

添加对[Matrix](https://matrix.org/)的支持

### 实现方法

[poljar/matrix-nio](https://github.com/poljar/matrix-nio)

### 接口

https://spec.matrix.org/v1.7/client-server-api/

### 备注

https://git.exozy.me/xtex/akari-bot/
https://github.com/xtexChooser/akari-bot

**Comment by OasisAkari** [comment]
如果确认工作一切正常的话那我就直接合并咯？

**Comment by xtexChooser** [comment]
它工作
