### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by liminghe1** [Teahouse-Studios/akari-bot#687]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [X] 我是群组的管理员，或群主或管理员允许机器人入群

### QQ群组类型

QQ群

### QQ号

864361013

### QQ群

190482004

### 入群方式

本群无特殊入群答案，支持搜索群号加群，无需二维码或入群链接。

### 群主或管理员同意

我是本群的群主

**Comment by OasisAkari** [comment]
申请已经发送，如果没有收到请在此issue下回复

**Comment by liminghe1** [comment]
没有收到申请，请问可否重发一次？

**Comment by OasisAkari** [comment]
尝试把入群条件临时改为无需管理员同意即可进群之后回复一下，机器人账号可能被风控了所以会收不到申请

**Comment by liminghe1** [comment]
已更改，抱歉刚才没及时看消息

**Comment by OasisAkari** [comment]
> 已更改，抱歉刚才没及时看消息

需要把管理员同意也关闭，如果确定关了尝试提供一个入群二维码给我再试试

**Comment by liminghe1** [comment]
![QQ图片20230713135254](https://github.com/Teahouse-Studios/akari-bot/assets/83519523/fa144c16-10e6-4d5f-a113-89b23467b95f)

**Comment by liminghe1** [comment]
再尝试一下？

**Comment by liminghe1** [comment]
感谢
