### ISSUE TITLE
[NEW]: 加入新群

### ISSUE THREAD

**Issue by wyuact** [Teahouse-Studios/akari-bot#688]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [X] 我是群组的管理员，或群主或管理员允许机器人入群

### QQ群组类型

QQ群

### QQ号

168502104

### QQ群

967596198

### 入群方式

本群无特殊入群答案，支持搜索群号加群，无需二维码或入群链接。

### 群主或管理员同意

我是本群的群主或管理员。

**Comment by OasisAkari** [comment]
申请已经发送，如果未收到请在本issue下回复

**Comment by wyuact** [comment]
未收到

**Comment by wyuact** [comment]
未收到

&nbsp;


168502104
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年7月13日(星期四) 中午11:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Teahouse-Studios/akari-bot] [NEW]: 加入新群 (Issue #688)






申请已经发送，如果未收到请在本问题下回复

—
直接回复此邮件，在GitHub上查看，或者取消订阅.
***@***.***与&gt;.

**Comment by DoroWolf** [comment]
已处理
