### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by anranshensha** [Teahouse-Studios/akari-bot#690]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [X] 我是群组的管理员，或群主或管理员允许机器人入群

### QQ群组类型

QQ群

### QQ号

3097762326

### QQ群

593014672

### 入群方式

本群无特殊入群答案，支持搜索群号加群，无需二维码或入群链接。

### 群主或管理员同意

我是本群的群主或管理员。

**Comment by OasisAkari** [comment]
尝试把入群条件临时改为无需管理员同意即可进群之后回复我一下，机器人账号可能被风控了所以会收不到申请

**Comment by DoroWolf** [comment]
请尝试将机器人邀请入群 目前机器人账号可能被风控

**Comment by DoroWolf** [comment]
请加机器人的好友后邀请机器人入群，入群申请可选填

**Comment by DoroWolf** [comment]
已处理
