### ISSUE TITLE
[NEW]: 添加好友

### ISSUE THREAD

**Issue by wyuact** [Teahouse-Studios/akari-bot#692]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [X] 我有必须在私聊使用机器人服务的需求。

### 用户 ID

168502104

### 群组 ID

738829671

### 理由

邀请加入我的群组

### 加好友方式

加我为好友无须特殊验证答案。

**Comment by DoroWolf** [comment]
已接受邀请
