### ISSUE TITLE
[FEATURE]: 建议制作docker版小可，方便批量部署

### ISSUE THREAD

**Issue by jhone22323232354** [Teahouse-Studios/akari-bot#712]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

建议给小可发行docker镜像，这样可以节省在不同服务器中安装依赖的时间

**Comment by Dianliang233** [comment]
如果你做好了的话可以直接pr

**Comment by DoroWolf** [comment]
推了，记得写~食用~使用方法
