### ISSUE TITLE
[BUG]: calc模块在Kook无法正常使用*

### ISSUE THREAD

**Issue by DoroWolf** [Teahouse-Studios/akari-bot#721]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法。

### 聊天平台

Kook

### 用户 ID

\

### 群组 ID

\

### 错误信息

表达式无效：{'unexpected character after line continuation character (<unknown>, line 1)'}

### 错误描述

~calc 命令在kook平台无法正常使用*和**。
另外，命令报错时应该去掉{'和'}。

### 复现方法

1. 执行 ~calc 1*2
2. 报错

### 本应发生的结果

正常返回结果。

**Comment by Dianliang233** [comment]
不了解这个平台
