### ISSUE TITLE
[FEATURE]: 适配更多消息类型和动作

### ISSUE THREAD

**Issue by SilianZ** [Teahouse-Studios/akari-bot#728]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

适配更多消息类型和动作：

1. 合并转发
2. 管理员方面的动作（如禁言等）

**Comment by SilianZ** [comment]
将就着做一些吧，如果可以的话可以再扩展一些

**Comment by Dianliang233** [comment]
合并转发已经有了。我们不做管理功能，所以如果你想要禁言的话附一个usecase

**Comment by DoroWolf** [comment]
> 合并转发已经有了。我们不做管理功能，所以如果你想要禁言的话附一个usecase

据我所知summary模块还是废弃的状态

**Comment by Dianliang233** [comment]
> > 合并转发已经有了。我们不做管理功能，所以如果你想要禁言的话附一个usecase
> 
> 据我所知summary模块还是废弃的状态

这个应该是upstream issue。

CC @OasisAkari

**Comment by SilianZ** [comment]
我其实不需要禁言功能，更需要的是加群管理，为了管理新群成员


合并转发已经有了。我们不做管理功能，所以如果你想要禁言的话附一个usecase
