### ISSUE TITLE
希望能够给我一个位子awa

### ISSUE THREAD

**Issue by z0z0r4** [Teahouse-Studios/akari-bot#81]
**我已阅读并同意 Teahouse Studios [服务条款](https://teahou.se/terms/) 和 [隐私政策](https://teahou.se/privacy)、问谛居 [用户协议](https://doc.wd-ljt.com/policy/user/) 和 [隐私政策](https://doc.wd-ljt.com/policy/privacy/) 和 小可服务 [隐私协议](/policy/privacy/)。**

**申请QQ号：3531890582

**申请QQ群： 962699166
（第二个群，606074824，另一个服务器，如果还有多余的名额的话（bushi，逃

人数都很少，不多的，偶尔查查wiki和~s
希望不会给茶馆管理带来困扰，打扰了

好友已经添加，从二号在tis群看到就一直在用，很喜欢awa，希望能获得一个名额~！

**Comment by OasisAkari** [comment]
麻烦向机器人发送一下要加入的群的邀请
