### ISSUE TITLE
[BUG]: 在周报中出现尝试发送空消息链

### ISSUE THREAD

**Issue by DSLZL** [Teahouse-Studios/akari-bot#818]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的问题，确定没有人提出过此问题/给出过其他解决方法。

### 聊天平台

QQ 群

### 用户 ID

2891362919

### 群组 ID

704397430

### 错误信息

发生错误：机器人尝试发送空消息链，请联系机器人开发者解决问题。
错误汇报地址：https://s.wd-ljt.com/botreportbug

### 错误描述

机器人发送周报显示错误

### 复现方法

无任何操作，周报发送消息产生

### 本应发生的结果

周报如往常一样顺利发送

**Comment by xiaoniaoawa** [comment]
同上，我刚要提交iessue就发现好像都有这问题（）

**Comment by taoqibaohalo** [comment]
同上：“发生错误：机器人尝试发送空消息链，请联系机器人开发者解决问题。错误汇报地址：https://s.wd-ljt.com/botreportbug”
