### ISSUE TITLE
[NEW]: 加入QQ群申请

### ISSUE THREAD

**Issue by xiaoniaoawa** [Teahouse-Studios/akari-bot#819]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [X] 我是群组的管理员，或群主或管理员允许机器人入群

### QQ群组类型

QQ群

### QQ号

3388617927

### QQ群

697905198（主群） 和 770146847（备份群）

### 入群方式

本群有特殊入群答案（人工审核，答案为Chromium），支持搜索群号加群，无需二维码或入群链接。

### 群主或管理员同意

我是本群的群主或管理员。
主群 身份自证截图
![image](https://github.com/Teahouse-Studios/akari-bot/assets/112697401/ee11db00-962e-4a7e-8811-d9d58b4f361b)

子群 身份自证截图
![image](https://github.com/Teahouse-Studios/akari-bot/assets/112697401/40064c33-2b5e-47f8-869d-d38516a76350)

### 备注

小可或许会被冷群冻死23333（）

**Comment by DoroWolf** [comment]
已发送请求，请检查是否收到
