### ISSUE TITLE
[BUG]: Cool Down 时区问题

### ISSUE THREAD

**Issue by Dianliang233** [Teahouse-Studios/akari-bot#837]
在非超级用户执行指令之后，程序将会执行以下操作：

2. 使用当前的时间戳减去数据库中 `timestamp` 一栏的时间戳得到该用户距上一次执行命令的时间 `now`。
3. 比较 `now` 与 `delay` 后返回剩余时间。
4. 重置用户的 Cool Down，将该用户ID和使用的指令名写入数据库。

`timestamp` 一栏是在数据库写入数据的时候自动添加的，默认的时区为 UTC+0，而中国是 UTC+8所以在执行第 2 个操作的时候 `now` 永远大于 `delay`，从而导致返回的剩余时间为0。

解决方法有两个，一是在重置 Cool Down 的时候手动存储 `timestamp` 为字符串，二是尝试更改 `timestamp` 存储的数据类型防止时区不同而带来的问题。

**Comment by OasisAkari** [comment]
第三个方法，不使用数据库存储cooldown信息
