### ISSUE TITLE
[NEW]: 

### ISSUE THREAD

**Issue by ZSY323** [Teahouse-Studios/akari-bot#859]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [X] 我是群组的管理员，或群主或管理员允许机器人入群

### QQ群组类型

QQ群

### QQ号

3589047740

### QQ群

834962118

### 入群方式

提交管理审核就行，随便回答

### 群主或管理员同意

我是本群的群主或管理员。

**Comment by DoroWolf** [comment]
已发送请求，请检查是否收到

**Comment by ZSY323** [comment]
被群主拒绝了草，能再发一遍吗（

**Comment by DoroWolf** [comment]
> 被群主拒绝了草，能再发一遍吗（

🙃
