### ISSUE TITLE
[REQUEST]: 申请添加花瓣

### ISSUE THREAD

**Issue by ZSY323** [Teahouse-Studios/akari-bot#883]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [X] 我是群组的管理员。

### 聊天平台

QQ 群

### 用户 ID

3589047740

### 群组 ID

834962118

### 花瓣数量

900

### 备注

太多了给少点也行，或者嫌少多给点也行（

**Comment by Dianliang233** [comment]
已授予 50
