### ISSUE TITLE
[REQUEST]: 申请添加花瓣

### ISSUE THREAD

**Issue by luo2f** [Teahouse-Studios/akari-bot#908]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [X] 我是群组的管理员。

### 聊天平台

QQ 频道

### 用户 ID

1375880562

### 群组 ID

QQ|Guild|21670681648222601|4557472

### 花瓣数量

30

### 备注

什么都可以哦，没有就算了吧

**Comment by DoroWolf** [comment]
已处理，请自行检查是否可用
