### ISSUE TITLE
[REQUEST]: 申请添加花瓣

### ISSUE THREAD

**Issue by SmallCoral** [Teahouse-Studios/akari-bot#912]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [X] 我是群组的管理员。

### 聊天平台

QQ 群

### 用户 ID

2153958001

### 群组 ID

QQ|Group|753761294

### 花瓣数量

3000

**Comment by DoroWolf** [comment]
已授予 100
