### ISSUE TITLE
[NEW]: 加入新群

### ISSUE THREAD

**Issue by taoqibaohalo** [Teahouse-Studios/akari-bot#950]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [X] 我是群组的管理员，或群主或管理员允许机器人入群

### QQ群组类型

QQ群

### QQ号

2293704782

### QQ群

610247039

### 入群方式

本群入群答案为:b站，支持搜索群号加群，无需二维码或入群链接。

### 群主或管理员同意

我是本群的群员，已获得管理同意
![accept-picture](https://github.com/Teahouse-Studios/akari-bot/assets/115784649/b634002e-1864-4b37-b54b-3f5f39e1f585)

**Comment by DoroWolf** [comment]
已发送请求
