### ISSUE TITLE
[NEW]: 小可你带我走吧

### ISSUE THREAD

**Issue by 2053628642** [Teahouse-Studios/akari-bot#951]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [X] 我是群组的管理员，或群主或管理员允许机器人入群

### QQ群组类型

QQ群

### QQ号

2053628642

### QQ群

414803123

### 入群方式

苔藓蔓延7*11*7

### 群主或管理员同意

https://i.postimg.cc/Jhzq7cD3/Screenshot-2023-09-04-23-41-41-158-com-tencent-mobileqq.png

**Comment by DoroWolf** [comment]
此群已违反[服务条款](https://bot.teahouse.team/wiki/tos)所定义的行为准则，出于诚信因素考虑，我们不会再次通过申请。
