### ISSUE TITLE
[REQUEST]: 申请添加花瓣

### ISSUE THREAD

**Issue by 4224GOEMON** [Teahouse-Studios/akari-bot#959]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [X] 我是群组的管理员。

### 聊天平台

QQ 群

### 用户 ID

2816937330

### 群组 ID

921772003

### 花瓣数量

15

**Comment by Dianliang233** [comment]
Granted
