### ISSUE TITLE
小可带我走吧

### ISSUE THREAD

**Issue by 2053628642** [Teahouse-Studios/akari-bot#963]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [X] 我是群组的管理员。

### 聊天平台

None

### 用户 ID

2053628642

### 群组 ID

414803123

### 花瓣数量

90

**Comment by 2053628642** [comment]
用户ID414803123
群号414803123

**Comment by Dianliang233** [comment]
granted
