### ISSUE TITLE
[REQUEST]: 申请添加花瓣

### ISSUE THREAD

**Issue by SmallCoral** [Teahouse-Studios/akari-bot#965]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [X] 我是群组的管理员。

### 聊天平台

QQ 群

### 用户 ID

QQ|2153958001

### 群组 ID

QQ|Group|753761294

### 花瓣数量

300

### 理由

群聊人数较多，每天有许多人需要gpt查阅资料/娱乐，100花瓣有点少，望不介意（

**Comment by DoroWolf** [comment]
已给予180，请勿滥用机器人功能。
