### ISSUE TITLE
[REQUEST]: 申请添加花瓣

### ISSUE THREAD

**Issue by xiaoniaoawa** [Teahouse-Studios/akari-bot#977]
### 开始之前……

- [X] 我已阅读并同意小可 [服务条款](https://bot.teahouse.team/wiki/tos) 和 Teahouse Studios [隐私政策](https://teahouse.team/privacy)。
- [X] 我是群组的管理员。

### 聊天平台

QQ 群

### 用户 ID

3388617927

### 群组 ID

QQ|Group|697905198

### 花瓣数量

200

### 理由

200个...还ok吧...
主要是有时候会白嫖几下GPT的代码233333
如果不行...给50-150个也不是不行

**Comment by DoroWolf** [comment]
已给予200
