### ISSUE TITLE
[建議]: 關於Cytoid的關卡標題

### ISSUE THREAD

**Issue by dyliu0306** [Teahouse-Studios/akari-bot#990]
### 开始之前……

- [X] 我已在[漏洞追踪器](https://github.com/Teahouse-Studios/bot/issues)中搜索过我的建议，确定没有人提出过此建议

### 建议描述

Cytoid的關卡名(title)支援html富文本，建議篩選出正確的標題字串出來

如#4 (<size=88><color='#EA0000'>Bl∞dmoon</color></size>)
![09a2c8c1-c22e-4280-9b32-9ff72a36e811-2](https://github.com/Teahouse-Studios/akari-bot/assets/89912899/541cf316-c55f-4274-94a1-29775221563a)

### 实现方法

level_data是api抓取的資料

如果標題含富文本的話
matches=re.findall(r"^([^<>]*?)(?=<)|>([^<>]+)<|>([^<>]+)|",level_data["title"])
title = ''.join(''.join(match).strip() for match in matches if any(match))

**Comment by OasisAkari** [comment]
已修复
